services:

  # Redis
  redis:
    image: redis:7-alpine
    container_name: xbooking_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - xbooking_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xbooking_web
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 Xbooking.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
       - "8000:8000"  # Map external port 8000 to internal port 8000  
    expose:
      - "8000"   # IMPORTANT: expose only internal port
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - xbooking_network

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xbooking_celery_worker
    restart: always
    command: celery -A Xbooking worker -l info --concurrency=2
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - xbooking_network

  # Celery Beat
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xbooking_celery_beat
    restart: always
    command: celery -A Xbooking beat -l info
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - xbooking_network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  xbooking_network:
    driver: bridge
